# MySQL database container
version: "3.0"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_app_docker
    volumes:
      - "./.data/db:/var/lib/mysql"
